name: Continuous Integration
on: [push]
env:
  BuildParameters.RestoreBuildProjects: '**/*.csproj'
  BuildParameters.TestProjects: '**/*[Tt]ests/*.csproj'
  BuildParameters.projects: '**/*.csproj'
  BuildParameters.sqlprojects: '**/*.sqlproj'  
jobs:
  build:
    name: Build and test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x     
      
      - name: Add Azure artifact
        run: dotnet nuget add source 'https://pkgs.dev.azure.com/e-LfH/_packaging/LearningHubFeed/nuget/v3/index.json' --name 'LearningHubFeed'  --username 'kevin.whittaker' --password ${{ secrets.AZURE_DEVOPS_PAT }} --store-password-in-clear-text

      
